name: "HA NVME-CLI"
description: "Home Assistant nvme-cli monitoring"
version: "1.0.6"
slug: "ha-nvmecli"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

privileged:
  - SYS_ADMIN
  - SYS_RAWIO
  - DAC_READ_SEARCH
full_access: true