name: "HA NVME-CLI"
description: "Home Assistant nvme-cli monitoring"
version: "1.0.5"
slug: "ha-nvmecli"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
devices:
  - /dev/nvme0n1
  - /dev/nvme1n1
  - /dev/sda
  - /dev/sdb
privileged:
  - SYS_ADMIN
  - SYS_RAWIO
  - DAC_READ_SEARCH